### ISSUE TITLE
友情链接无法正常显示

### ISSUE THREAD

**Issue by JohnNiang** [CodeLunatic/halo-theme-simple-bootstrap#1]
未分类的友情链接似乎无法正常显示。

**Comment by CodeLunatic** [comment]
感谢大佬，今天就更改已知问题

发送自 Windows 10 版邮件应用

发件人: John Niang
发送时间: 2019年10月23日 22:11
收件人: CodeLunatic/halo-theme-simple-bootstrap
抄送: Subscribed
主题: [CodeLunatic/halo-theme-simple-bootstrap] 友情链接无法正常显示 (#1)

未分类的友情链接似乎无法正常显示。
