### ISSUE TITLE
更新1.2.0版halo后，将主题更细为最新版主页框架错乱

### ISSUE THREAD

**Issue by QianXun0827** [CodeLunatic/halo-theme-simple-bootstrap#10]
![image](https://user-images.githubusercontent.com/40862062/71860511-3e32e180-312e-11ea-9558-9446c2b11433.png)
如图所示

**Comment by QianXun0827** [comment]
F12打开控制台无报错
![image](https://user-images.githubusercontent.com/40862062/71860577-733f3400-312e-11ea-848a-901855e1d5a8.png)

**Comment by CodeLunatic** [comment]
有时间我会大改，匹配上1.2.0版本的，请不要担心，改好会通知大家的

**Comment by QianXun0827** [comment]
> 有时间我会大改，匹配上1.2.0版本的，请不要担心，改好会通知大家的

感谢大佬~就等你的改版啦

**Comment by jiangxhect** [comment]
日志显示不出来，麻烦一并改版，期待新版本。

**Comment by CodeLunatic** [comment]
@QianXun0827 这个框架错乱的页面是首页吗，我无法复现，可以提供一下控制台network的完整截图吗？

**Comment by QianXun0827** [comment]
> @QianXun0827 这个框架错乱的页面是首页吗，我无法复现，可以提供一下控制台network的完整截图吗？

我重新装了一次后台服务又没有问题了，现在已经恢复正常使用。可能是我自己的配置问题T.T
