### ISSUE TITLE
标签及文章目录乱掉

### ISSUE THREAD

**Issue by punklu** [CodeLunatic/halo-theme-simple-bootstrap#11]
![image](https://user-images.githubusercontent.com/50325831/74096054-8c277480-4b34-11ea-94cb-101656353cc3.png)
![image](https://user-images.githubusercontent.com/50325831/74096056-90ec2880-4b34-11ea-98ae-cd27c97f1f01.png)

地址：https://www.punklu.tech/archives/%E9%80%86%E5%90%91%E5%B7%A5%E7%A8%8B%E6%A0%B8%E5%BF%83%E5%8E%9F%E7%90%86%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%E9%80%86%E5%90%91%E5%88%86%E6%9E%90helloworld%E7%A8%8B%E5%BA%8Fmd

求解决

**Comment by CodeLunatic** [comment]
```javascript
jquery.min.js:2 Uncaught Error: code length overflow. (1676>1056)
    at Function.e.createData (social-share.min.js:formatted:239)
    at e.makeImpl (social-share.min.js:formatted:131)
    ... ...
```

报错的原因是因为文章链接过长的原因导致微信分享二维码生成错误，你可以到后台设置一下文章的链接，或者直接关闭主题的分享功能

---

标签错位的原因需要结合md文档来分析，你可以将你的md文档通过[临时分享平台](https://send.firefox.com/)临时分享过来
