### ISSUE TITLE
cdn.bootcss.com 部分国内地址无法访问

### ISSUE THREAD

**Issue by SaintLoong** [CodeLunatic/halo-theme-simple-bootstrap#13]
cdn.bootcss.com 部分国内地址无法访问，导致样式丢失，现在您的博客访问也是丢失了样式，更换国内cdn https://lib.baomitu.com，但还是有js中引用的 github.mini.css用的是 国外的cdn，因为前端实在不熟悉，麻烦看下更换国内cdn吧

请求网址:https://cdn.bootcss.com/highlight.js/9.15.10/styles/github.min.css
请求方法:GET
状态码:
404

**Comment by CodeLunatic** [comment]
问题已经修复了，麻烦手动更新一下主题，并且把主题设置里面的`代码样式地址`也更改掉

样式CSS在这里：https://www.jsdelivr.com/package/npm/highlight.js?path=styles
