### ISSUE TITLE
在线更新主题后，首页样式不大对劲

### ISSUE THREAD

**Issue by punklu** [CodeLunatic/halo-theme-simple-bootstrap#18]
![image](https://user-images.githubusercontent.com/50325831/75127014-9bdbb700-56f7-11ea-9c07-1338cf285f2b.png)

网站地址：punklu.tech

**Comment by punklu** [comment]
页面布局过于紧凑，不知道是BUG还是FEATURE？

**Comment by CodeLunatic** [comment]
因为布局方式重构，所以你需要`Ctrl + F5`强制刷新一下,感谢支持
