### ISSUE TITLE
代码风格

### ISSUE THREAD

**Issue by EthanLoving** [CodeLunatic/halo-theme-simple-bootstrap#21]
代码样式有黑色主题的吗

**Comment by CodeLunatic** [comment]
修改代码样式为这个链接 https://cdn.staticfile.org/highlight.js/9.18.1/styles/monokai-sublime.min.css

**Comment by EthanLoving** [comment]
> https://cdn.staticfile.org/highlight.js/9.18.1/styles/monokai-sublime.min.css

嗯嗯 谢谢
