### ISSUE TITLE
halo-theme-simple-bootstrap文章别名无法配置

### ISSUE THREAD

**Issue by xulongju** [CodeLunatic/halo-theme-simple-bootstrap#22]
你好：
很喜欢这个主题，在使用中无法设置【文章别名】，保存后就变成空白了。
![image](https://user-images.githubusercontent.com/20881910/77318278-ca28d280-6d47-11ea-8999-b997b2e857f1.png)
导致我访问的url，只能是：
![image](https://user-images.githubusercontent.com/20881910/77318336-de6ccf80-6d47-11ea-8138-4653f92691db.png)
不能像你的文章一样：https://halo.cyblogs.top/archives/the-secret-to-effective-learning

请问如何调整，谢谢。

**Comment by CodeLunatic** [comment]
可能是你使用了高版本的主程序，这个主题当前最高支持1.2.0版本的Release版本。

**Comment by xulongju** [comment]
我现在用的版本为1.2.0

**Comment by CodeLunatic** [comment]
主题已经更新到1.3.0Release了
