### ISSUE TITLE
导航栏中的链接不支持绝对地址？

### ISSUE THREAD

**Issue by Kherrisan** [CodeLunatic/halo-theme-simple-bootstrap#27]
在 Halo 的管理页面里添加了菜单项，并且使用的是其他域名的绝对地址，在 simple-bootstrap 主题中，绝对地址似乎也变成了相对当前域名的链接，导致无法访问了。如图：
![](https://s1.ax1x.com/2020/04/04/GwuaBF.png)

**Comment by CodeLunatic** [comment]
你可以通过修改module文件夹里面的navbar.ftl文件中的一行。之前为了修复某个问题才加上的逻辑运算，你可以去掉。
![image](https://user-images.githubusercontent.com/40259896/78420048-41cafb80-767e-11ea-8a84-946dd497f371.png)
