### ISSUE TITLE
从文章详情界面打开图片、日志时路径出错

### ISSUE THREAD

**Issue by punklu** [CodeLunatic/halo-theme-simple-bootstrap#4]
在文章详情里点击图片、日志链接时，域名后显示的是archives/photos

**Comment by CodeLunatic** [comment]
可以将问题描述的更清楚一些吗？

**Comment by punklu** [comment]
在文章详情页面，点击菜单里的照片链接
![image](https://user-images.githubusercontent.com/50325831/69644746-043ade00-10a0-11ea-8ef4-7f04833644af.png)
域名后的后缀应该是photos，但是现在却是archives/photos，导致报404的错
![image](https://user-images.githubusercontent.com/50325831/69644819-1caaf880-10a0-11ea-84ec-b0798b50778c.png)

**Comment by CodeLunatic** [comment]
这个你可以到后台的 【外观 - 菜单】 界面更改一下路径，如下：
![image](https://user-images.githubusercontent.com/40259896/69648881-1ec48580-10a7-11ea-81f9-d10a92acbbdc.png)
注意前面的`/`，后期会改进这个问题的，感谢你的使用

**Comment by punklu** [comment]
好的，很喜欢这个主题，希望一直维护下去
