### ISSUE TITLE
文章目录显示建议

### ISSUE THREAD

**Issue by blankhang** [CodeLunatic/halo-theme-simple-bootstrap#6]
代码高亮如果能配置成多种样式可选就好了= =
部分 bash/sh 的命令颜色 没有高亮 不知可否完善
目录列表貌似字体和间隔过大
可否参考这位的样式
https://www.imkun.dev/archives/Fantastic%20%E4%B8%BB%E9%A2%98%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97
感谢

**Comment by CodeLunatic** [comment]
采纳，当前主题只是我喜欢简洁风的一个初期版本，可能以后会变得花里胡哨，也有可能会保持简洁，佛系更新，敬请等待

**Comment by xiaofsu** [comment]
现有代码没有高亮看着有些别扭。不知道`csdn`那样的代码风格怎么样，可能和现有主题的简洁风有些冲突。

可以看到代码块也是黑灰色的，不突出...

![image](https://user-images.githubusercontent.com/46067472/71496876-8cbfc080-2890-11ea-88e0-553808d2a0c7.png)

很棒的主题风格，加油！

**Comment by CodeLunatic** [comment]
“目录列表貌似字体和间隔过大”，已经尝试修改，但与主题风格冲突，其他的已经修复

**Comment by CodeLunatic** [comment]
“目录列表貌似字体和间隔过大”，已经尝试修改，但与主题风格冲突，其他的已经修复
