### ISSUE TITLE
目录进度与文章进度是否能够分开更改

### ISSUE THREAD

**Issue by xiaofsu** [CodeLunatic/halo-theme-simple-bootstrap#7]
![image](https://user-images.githubusercontent.com/46067472/71497045-5fbfdd80-2891-11ea-9e40-8db451c34881.png)

---

当前主题只能同时修改 `是否使用阅读进度条和目录进度：`
能否进行分别修改
因为之前使用的主题，使用了标题之后显示不明显，所以可能不太注意标题设置

Thanks♪(･ω･)ﾉ

**Comment by CodeLunatic** [comment]
好的，没问题

**Comment by CodeLunatic** [comment]
已更新
